### ISSUE TITLE
theme visibility filter problem with $

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3912]
On first look everything looked correct
![image](https://user-images.githubusercontent.com/5429548/62115782-4a7e5d00-b2b9-11e9-937a-1e37006d4513.png)
But I couldn't get it to work.

if I do this
` var_dump($kpage); print_a($kpage); `
result is:
![image](https://user-images.githubusercontent.com/5429548/62116443-76e6a900-b2ba-11e9-8546-dc5c43a893eb.png)

so I checked the database and there is value 
 
![image](https://user-images.githubusercontent.com/5429548/62116615-c4fbac80-b2ba-11e9-9aa5-061675891acf.png)

so of course this test fails

```
          var_dump($lastChar); print_a($lastChar);  
					if($lastChar === '$') // script name match.
					{  
```
![image](https://user-images.githubusercontent.com/5429548/62116744-fd02ef80-b2ba-11e9-9f3d-9eea121aae7c.png)

If I check Database Tools/Prefs Editor, it displays
![image](https://user-images.githubusercontent.com/5429548/62116868-38052300-b2bb-11e9-9b98-d070b1091141.png)

Maybe it's environment issue (xampp), no idea, but that check should count with both version of $.

**Comment by Jimmi08** [comment]
Adding this line helped:  `$kpage = html_entity_decode($kpage, ENT_NOQUOTES, 'UTF-8');`

**Comment by Moc** [comment]
Confirmed

**Comment by CaMer0n** [comment]
@Jimmi08 Please re-test and open again if necessary. Thank you.

**Comment by CaMer0n** [comment]
As of v2.3.1 one can now use ```:(e_ROUTE)``` for theme layout switching in the Theme Manager.
eg. ```:news/list/item```

![image](https://user-images.githubusercontent.com/2825679/107885766-eded8d80-6eb0-11eb-8a13-2fab42160911.png)

In the browser, add `?[debug=paths!]` to the SEF URL to find the current value of  `e_ROUTE` listed in the footer of the page. (must be logged in as admin)   

![image](https://user-images.githubusercontent.com/2825679/107886020-45402d80-6eb2-11eb-9ef2-b2f293245225.png)

 It also accepts partial matches. 
eg. You could enter `:vstore` for all SEF urls of the vstore plugin, or `:news/list` to match all `news/list` routes such as: 

- news/list/all
- news/list/short
- news/list/category
- news/list/day
- news/list/month
- news/list/tag
- news/list/author

 I also plan to add a pop-up for when we type ':' for a list of available routes. (it may go into this release or a future one)

@Moc @realmontazeri (for user and dev documentation) 

@Jimmi08 @fizi fyi.

**Comment by CaMer0n** [comment]
Popup route menu example: 

![image](https://user-images.githubusercontent.com/2825679/108277135-ca834680-712d-11eb-9470-212c0a3a5017.png)

@Moc @Jimmi08 @fizi @realmontazeri

**Comment by CaMer0n** [comment]
### TODO
- [ ] Remove delay while typing after ':'
- [ ] Fix the value reverting to "_blank/" when pressing ENTER. 
- [ ] Added e_ROUTE value while SEF is not active.

**Comment by Jimmi08** [comment]
@CaMer0n 

Standalone page (without chapter) has with SEF_URL e_ROUTE 
` page/book/index`

I don't think it is correct, is it?

**Comment by CaMer0n** [comment]
@Jimmi08 You're right, that is incorrect. It should be `page/view/other`

**Comment by Jimmi08** [comment]
@CaMer0n 
when I use `:news/view/item` , it works
if I use just` :news`  it stopped to work

Screen just to be sure  (no mistypo)
![image](https://user-images.githubusercontent.com/5429548/109329795-4f234280-785b-11eb-8d24-bc1f72310b19.png)

**Comment by Jimmi08** [comment]
@CaMer0n maybe just question

If Frontpage is set to custom URL, that is a page in my case, what should be e_ROUTE?

- you can't use the custom page option for Frontpage, because then only the content of that page is used, so you do this:

![image](https://user-images.githubusercontent.com/5429548/111122906-fba93800-856e-11eb-968b-9d90cbc4df15.png)

It works, only "FRONTPAGE" fails in detecting layout. 

e_ROUTE is `page/book/index`   which looks weird. 

This was fix:
![image](https://user-images.githubusercontent.com/5429548/111123241-622e5600-856f-11eb-89a3-976c6698d8c6.png)

Thanks
